# Generated by Django 3.2.8 on 2021-12-10 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0021_alter_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
