# Generated by Django 3.2.8 on 2021-12-11 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0025_auto_20211211_1009'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='reply',
            new_name='parent',
        ),
    ]
